packages:
  - 'app'
  - 'kyc-app'
  - 'server'
  - 'common/*'

catalog:
  '@pandacss/dev': '^1.8.1'
  '@rainbow-me/rainbowkit': '^2.2.10'
  '@tanstack/react-query': '^5.90.19'
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  'react-server-dom-webpack': '~19.2.3'
  'swagger-typescript-api': '^13.2.17'
  'typescript': '^5.7.3'
  'viem': '2.38.0'
  'wagmi': '^2.19.3'
  'waku': '1.0.0-alpha.3'
  '@types/node': '^22.10.5'
  '@types/react': '^19.0.5'
  '@types/react-dom': '^19.0.3'
  '@vitejs/plugin-react': '^5.1.0'
  'babel-plugin-react-compiler': '^1.0.0'
  'vite-plugin-svgr': '^4.5.0'
